#!/usr/bin/env node

/**
 * Generates supabase/seed.sql from all JSON lesson files in data/lessons/
 */

const fs = require('fs')
const path = require('path')

const lessonsDir = path.join(__dirname, '..', 'data', 'lessons')
const outputPath = path.join(__dirname, '..', 'supabase', 'seed.sql')

// Read all lesson JSON files sorted by name
const files = fs.readdirSync(lessonsDir)
  .filter(f => f.endsWith('.json'))
  .sort()

const lessons = files.map(f => {
  const raw = fs.readFileSync(path.join(lessonsDir, f), 'utf8')
  return JSON.parse(raw)
})

// Escape single quotes for SQL
function esc(str) {
  if (str === null || str === undefined) return 'NULL'
  return "'" + String(str).replace(/'/g, "''") + "'"
}

function escJsonb(val) {
  return "'" + JSON.stringify(val).replace(/'/g, "''") + "'"
}

let sql = `-- ============================================
-- Seed: All 20 lessons across 4 phases
-- Auto-generated by scripts/generate-seed.js
-- ============================================

-- Clear existing data (in reverse dependency order)
DELETE FROM exercises;
DELETE FROM lessons;

`

for (let i = 0; i < lessons.length; i++) {
  const lesson = lessons[i]
  const lessonId = i + 1

  sql += `-- ============================================\n`
  sql += `-- Lesson ${lessonId}: ${lesson.title}\n`
  sql += `-- ============================================\n`

  sql += `INSERT INTO lessons (id, phase, order_num, title, description, difficulty, estimated_minutes, content_md)\n`
  sql += `VALUES (${lessonId}, ${lesson.phase}, ${lesson.order_num}, ${esc(lesson.title)},\n`
  sql += `  ${esc(lesson.description)},\n`
  sql += `  ${esc(lesson.difficulty)}, ${lesson.estimated_minutes},\n`
  sql += `  ${esc(lesson.content_md)});\n\n`

  if (lesson.exercises && lesson.exercises.length > 0) {
    for (const ex of lesson.exercises) {
      sql += `INSERT INTO exercises (lesson_id, order_num, title, prompt, starter_code, solution, hints, test_cases, requires_plot)\n`
      sql += `VALUES (${lessonId}, ${ex.order_num}, ${esc(ex.title)},\n`
      sql += `  ${esc(ex.prompt)},\n`
      sql += `  ${esc(ex.starter_code)},\n`
      sql += `  ${esc(ex.solution)},\n`
      sql += `  ${escJsonb(ex.hints)},\n`
      sql += `  ${escJsonb(ex.test_cases)},\n`
      sql += `  ${ex.requires_plot || false});\n\n`
    }
  }

  sql += '\n'
}

// Reset the sequence so future inserts get the right IDs
sql += `-- Reset sequences\n`
sql += `SELECT setval('lessons_id_seq', (SELECT MAX(id) FROM lessons));\n`
sql += `SELECT setval('exercises_id_seq', (SELECT MAX(id) FROM exercises));\n`

fs.writeFileSync(outputPath, sql)
console.log(`Generated ${outputPath} with ${lessons.length} lessons`)
